#!/usr/bin/env node
// coverage-matrix.test.mjs — per-team story × AC → TC coverage matrix
// generated by build-index.mjs.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const BUILD_INDEX = path.join(REPO_ROOT, 'scripts', 'build-index.mjs');

let passed = 0;
let failed = 0;
function assert(cond, msg) {
  if (cond) { passed++; process.stdout.write(`  ✓ ${msg}\n`); }
  else { failed++; process.stdout.write(`  ✗ ${msg}\n`); }
}

function run(args) {
  const r = spawnSync('node', [BUILD_INDEX, ...args], { encoding: 'utf8' });
  return { code: r.status, out: (r.stdout || '') + (r.stderr || '') };
}

const STORY = `---
title: "FIX-1 — Search filter"
type: story
ticket: FIX-1
sprint: "2026-S27"
priority: medium
status: in-progress
ac_audit_status: done
linked_test_cases: [TC-SEARCH-900, TC-SEARCH-901]
linked_bugs: []
review_status: not-reviewed
language: en
tags: [story]
updated: 2026-07-06
---

# FIX-1 — Search filter

## Acceptance criteria

### AC-1: Filter by date range
text

### AC-2: Empty state
text
`;

const LEGACY_STORY = `---
title: "FIX-2 — Legacy"
type: story
ticket: FIX-2
sprint: "2026-S27"
priority: low
status: in-progress
ac_audit_status: pending
linked_test_cases: [TC-SEARCH-902]
linked_bugs: []
review_status: not-reviewed
language: en
tags: [story]
updated: 2026-07-06
---

# FIX-2 — Legacy

## Acceptance criteria

Prose without structured headings.
`;

function tc(id, { covers = null, stories = '[FIX-1]', auto = 'manual-only', extra = '' } = {}) {
  return `---
title: "${id} — check"
type: test-case
id: ${id}
area: search
level: ui
coverage: positive
status: active
automation_status: ${auto}
linked_stories: ${stories}
${covers === null ? '' : `covers_ac: ${covers}\n`}review_status: not-reviewed
${extra}language: en
tags: [search]
updated: 2026-07-06
---

# ${id}
`;
}

async function buildFixture() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'kqa-matrix-'));
  const team = path.join(root, 'teams', 'fix-team');
  await fs.mkdir(path.join(team, 'stories', 'FIX-1-search'), { recursive: true });
  await fs.mkdir(path.join(team, 'stories', 'FIX-2-legacy'), { recursive: true });
  await fs.mkdir(path.join(team, 'test-cases', 'search'), { recursive: true });
  await fs.writeFile(path.join(team, 'stories', 'FIX-1-search', 'story.md'), STORY);
  await fs.writeFile(path.join(team, 'stories', 'FIX-2-legacy', 'story.md'), LEGACY_STORY);
  await fs.writeFile(
    path.join(team, 'test-cases', 'search', 'tc-search-900.md'),
    tc('TC-SEARCH-900', {
      covers: '[AC-1]',
      auto: 'automated',
      extra: 'last_run: 2026-07-05\nlast_result: passed\n',
    }));
  await fs.writeFile(
    path.join(team, 'test-cases', 'search', 'tc-search-901.md'),
    tc('TC-SEARCH-901')); // no covers_ac → unmapped
  await fs.writeFile(
    path.join(team, 'test-cases', 'search', 'tc-search-902.md'),
    tc('TC-SEARCH-902', { stories: '[FIX-2]' })); // story without AC headings
  return { root, matrixPath: path.join(team, 'coverage-matrix.md') };
}

async function main() {
  process.stdout.write('coverage-matrix.test.mjs\n');
  process.stdout.write('========================\n\n');

  const { root, matrixPath } = await buildFixture();
  const w = run(['--root', root]);
  assert(w.code === 0, 'build-index runs clean on the fixture');

  let matrix = '';
  try {
    matrix = await fs.readFile(matrixPath, 'utf8');
  } catch { /* missing */ }
  assert(matrix.length > 0, 'coverage-matrix.md generated for the team');
  assert(matrix.includes('Coverage MAP (not proof)'),
    'header carries the map-not-proof disclaimer');
  assert(/\| FIX-1 \| AC-1 \| TC-SEARCH-900 \| automated \| 2026-07-05 passed \|/.test(matrix),
    'AC-1 row shows covering TC + automation + last run');
  assert(/\| FIX-1 \| AC-2 \| ⚠ uncovered \| — \| — \|/.test(matrix),
    'AC-2 row shows ⚠ uncovered');
  assert(/\(unmapped\)/.test(matrix) && /TC-SEARCH-901/.test(matrix),
    'TC without covers_ac appears in the (unmapped) row');
  assert(/FIX-2/.test(matrix) && /no structured ACs — excluded from coverage/.test(matrix),
    'story without AC headings gets the excluded-visibility row');

  // Idempotent + check clean
  const chk = run(['--root', root, '--check']);
  assert(chk.code === 0, '--check clean right after generation');

  // Drift: delete a row → --check flags it
  await fs.writeFile(matrixPath, matrix.replace(/\| FIX-1 \| AC-2 \|[^\n]*\n/, ''));
  const chk2 = run(['--root', root, '--check']);
  assert(chk2.code === 1 && /coverage-matrix/.test(chk2.out),
    '--check detects a hand-deleted matrix row');

  process.stdout.write(`\n${passed} passed, ${failed} failed\n`);
  if (failed > 0) process.exit(1);
  process.stdout.write('✓ all coverage-matrix tests passed\n');
}

main().catch((err) => {
  process.stderr.write(`coverage-matrix.test.mjs crashed: ${err.stack}\n`);
  process.exit(1);
});
