#!/usr/bin/env node
// migrate-v1.7-to-v1.8.test.mjs — guards the v1.7 -> v1.8 migration.
//
// Builds a temp fake "source" (a fresh v1.8 template) and a temp fake
// "target" (an existing v1.7 brain with real user data), runs the
// migration via its exported migrate() helper, and asserts:
//   - a framework file was copied source -> target,
//   - the CHAT-HANDOFF.md line was removed from the target .gitignore,
//   - sessions/ exists in the target,
//   - user data (teams/ + JOURNAL.md content) was left UNTOUCHED,
//   - re-running is idempotent (no second copy, no crash),
//   - the pure gitignore/snapshotignore strippers behave.
//
// Run: node scripts/tests/migrate-v1.7-to-v1.8.test.mjs

import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCRIPT = path.join(REPO_ROOT, 'scripts', 'migrate-v1.7-to-v1.8.mjs');

const mod = await import(pathToFileURL(SCRIPT).href);
const {
  migrate,
  stripChatHandoffFromGitignore,
  stripChatHandoffFromSnapshotignore,
} = mod;

let passed = 0;
let failed = 0;
const failures = [];
function assert(cond, msg) {
  if (cond) { passed++; } else { failed++; failures.push(msg); }
}

const JOURNAL_CONTENT = `# JOURNAL

## 2026-06-01 — real work
STATE: shipped the login regression suite
NEXT: triage flaky checkout test
`;

const TEAM_STORY = `---
title: "Login bug"
type: story
---
# Login bug
real user data — must survive the migration verbatim.
`;

async function buildSource(root) {
  // A minimal fresh v1.8 template: just enough of the allowlist to prove
  // copying works. We seed two distinct allowlisted files.
  await fs.mkdir(path.join(root, '.github', 'prompts'), { recursive: true });
  await fs.mkdir(path.join(root, 'sessions'), { recursive: true });
  await fs.writeFile(
    path.join(root, '.github', 'prompts', 'session-end.prompt.md'),
    '# session-end (v1.8 autonomous)\n'
  );
  await fs.writeFile(path.join(root, 'sessions', 'README.md'), '# sessions/\nper-session logs.\n');
  await fs.writeFile(path.join(root, 'VERSION'), '1.8.0\n');
}

async function buildTarget(root) {
  // An existing v1.7 brain with REAL user data + the legacy CHAT-HANDOFF
  // wiring that v1.8 retires.
  await fs.mkdir(path.join(root, 'teams', 'acme', 'stories', 'PROJ-1'), { recursive: true });
  await fs.writeFile(
    path.join(root, 'teams', 'acme', 'stories', 'PROJ-1', 'story.md'),
    TEAM_STORY
  );
  await fs.writeFile(path.join(root, 'JOURNAL.md'), JOURNAL_CONTENT);
  await fs.writeFile(path.join(root, 'VERSION'), '1.7.0\n');

  // Pre-existing (stale) versions of allowlist files so we can prove overwrite.
  await fs.mkdir(path.join(root, '.github', 'prompts'), { recursive: true });
  await fs.writeFile(
    path.join(root, '.github', 'prompts', 'session-end.prompt.md'),
    '# session-end (OLD v1.7 — 3-question interview)\n'
  );

  // A stray root CHAT-HANDOFF.md (gitignored ephemeral state on disk).
  await fs.writeFile(path.join(root, 'CHAT-HANDOFF.md'), '# stale handoff\n');

  // .gitignore with the v1.7 CHAT-HANDOFF block.
  await fs.writeFile(
    path.join(root, '.gitignore'),
    [
      '.secrets',
      '',
      '# Chat handoff state — ephemeral session context, not knowledge.',
      '# Generated by /chat-handoff. Included in snapshot ZIPs for personal',
      '# laptop-swap recovery (see AGENTS.md §3 + §8).',
      'CHAT-HANDOFF.md',
      '',
      '# Import staging — generated by scripts/import-prior-brain.mjs.',
      'imports/',
      '',
    ].join('\n')
  );

  // .snapshotignore with the inline CHAT-HANDOFF mention.
  await fs.writeFile(
    path.join(root, '.snapshotignore'),
    [
      '# Snapshots are PERSONAL recovery archives.',
      '# They include credentials (.env, client-secrets/, .secrets, CHAT-HANDOFF.md, .cache/) ARE included.',
      '',
      'versions/',
      'node_modules/',
      '',
    ].join('\n')
  );
}

async function main() {
  // ---- pure unit tests on the strippers ----
  {
    const gi = [
      '.secrets',
      '',
      '# Chat handoff state — ephemeral session context, not knowledge.',
      '# laptop-swap recovery (see AGENTS.md §3 + §8).',
      'CHAT-HANDOFF.md',
      '',
      'imports/',
      '',
    ].join('\n');
    const { content, removed } = stripChatHandoffFromGitignore(gi);
    assert(removed === true, 'stripGitignore reports removed');
    assert(!content.includes('CHAT-HANDOFF.md'), 'stripGitignore drops the entry line');
    assert(!/Chat handoff state/.test(content), 'stripGitignore drops the comment header');
    assert(content.includes('imports/'), 'stripGitignore keeps unrelated entries');
    // Idempotent: second pass is a no-op.
    const second = stripChatHandoffFromGitignore(content);
    assert(second.removed === false, 'stripGitignore second pass is a no-op');
  }
  {
    const si = '# creds (.env, .secrets, CHAT-HANDOFF.md, .cache/) included.\nversions/\n';
    const { content, removed } = stripChatHandoffFromSnapshotignore(si);
    assert(removed === true, 'stripSnapshotignore reports removed');
    assert(!content.includes('CHAT-HANDOFF.md'), 'stripSnapshotignore drops the inline mention');
    assert(content.includes('.secrets') && content.includes('.cache/'), 'stripSnapshotignore keeps the rest of the sentence');
    assert(content.includes('versions/'), 'stripSnapshotignore keeps unrelated lines');
  }

  // ---- end-to-end migration on temp source + target ----
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'kqa-mig-17-18-'));
  const source = path.join(tmp, 'source');
  const target = path.join(tmp, 'target');
  await fs.mkdir(source, { recursive: true });
  await fs.mkdir(target, { recursive: true });
  await buildSource(source);
  await buildTarget(target);

  const report = await migrate({ source, target });

  // A framework file was copied.
  assert(report.copied.length > 0, 'at least one framework file was copied');
  assert(
    report.copied.some((r) => r.rel === '.github/prompts/session-end.prompt.md'),
    'session-end.prompt.md is reported as copied'
  );
  const copiedPrompt = await fs.readFile(
    path.join(target, '.github', 'prompts', 'session-end.prompt.md'),
    'utf8'
  );
  assert(/autonomous/.test(copiedPrompt), 'target session-end.prompt.md now has v1.8 content (overwritten)');
  const copiedVersion = (await fs.readFile(path.join(target, 'VERSION'), 'utf8')).trim();
  assert(copiedVersion === '1.8.0', 'VERSION bumped to 1.8.0 in target');

  // CHAT-HANDOFF removed from .gitignore.
  const gi = await fs.readFile(path.join(target, '.gitignore'), 'utf8');
  assert(!gi.includes('CHAT-HANDOFF.md'), 'CHAT-HANDOFF.md line removed from target .gitignore');
  assert(gi.includes('imports/'), '.gitignore keeps unrelated entries after migration');

  // CHAT-HANDOFF removed from .snapshotignore.
  const si = await fs.readFile(path.join(target, '.snapshotignore'), 'utf8');
  assert(!si.includes('CHAT-HANDOFF.md'), 'CHAT-HANDOFF.md removed from target .snapshotignore');

  // Stray root CHAT-HANDOFF.md deleted.
  const handoffGone = !(await fs.access(path.join(target, 'CHAT-HANDOFF.md')).then(() => true).catch(() => false));
  assert(handoffGone, 'stray root CHAT-HANDOFF.md was deleted');

  // sessions/ exists.
  const sessionsExists = await fs.access(path.join(target, 'sessions')).then(() => true).catch(() => false);
  assert(sessionsExists, 'sessions/ exists in target');
  const sessionsReadme = await fs.access(path.join(target, 'sessions', 'README.md')).then(() => true).catch(() => false);
  assert(sessionsReadme, 'sessions/README.md was copied into target');

  // User data UNTOUCHED.
  const journalAfter = await fs.readFile(path.join(target, 'JOURNAL.md'), 'utf8');
  assert(journalAfter === JOURNAL_CONTENT, 'JOURNAL.md content left UNTOUCHED');
  const storyAfter = await fs.readFile(
    path.join(target, 'teams', 'acme', 'stories', 'PROJ-1', 'story.md'),
    'utf8'
  );
  assert(storyAfter === TEAM_STORY, 'teams/ user data left UNTOUCHED');

  // Idempotent re-run: no framework copies the second time, no crash.
  const report2 = await migrate({ source, target });
  assert(report2.copied.length === 0, 're-run copies nothing (idempotent)');
  const journalAfter2 = await fs.readFile(path.join(target, 'JOURNAL.md'), 'utf8');
  assert(journalAfter2 === JOURNAL_CONTENT, 'JOURNAL.md still untouched after re-run');
  const giAfter2 = await fs.readFile(path.join(target, '.gitignore'), 'utf8');
  assert(!giAfter2.includes('CHAT-HANDOFF.md'), '.gitignore stays clean after re-run');

  await fs.rm(tmp, { recursive: true, force: true });

  process.stdout.write(`\nmigrate-v1.7-to-v1.8: ${passed} passed, ${failed} failed\n`);
  if (failed) {
    for (const f of failures) process.stdout.write(`  ✗ ${f}\n`);
    process.exit(1);
  }
  process.stdout.write('✓ all migrate-v1.7-to-v1.8 tests passed\n');
}

main().catch((err) => {
  process.stderr.write(`migrate-v1.7-to-v1.8 test crashed: ${err.stack || err.message}\n`);
  process.exit(1);
});
