#!/usr/bin/env node
// validate.mjs — frontmatter + integrity + PII check across the brain.
//
// Walks all .md files (except exempted README/AGENTS/INDEX/etc.),
// parses frontmatter, and checks:
//   1. Required base fields present (title, type, language, tags, updated)
//   2. type value is in the allowed set
//   3. status value is type-specific and valid
//   4. language is 'en' (template invariant)
//   5. updated is YYYY-MM-DD shaped
//   6. Type-specific vocab fields for stories, test cases, bugs, reviews
//   7. PII patterns in body (best-effort regex scan; warns only)
//
// Exit codes:
//   0 — all clean (PII warnings still print but don't fail)
//   1 — schema violations, or PII warnings when --strict-pii is enabled
//
// Usage:
//   node scripts/validate.mjs                # validate whole brain
//   node scripts/validate.mjs <path>         # validate one file
//   node scripts/validate.mjs --strict-pii   # treat PII warnings as errors

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const ALLOWED_TYPES = new Set([
  'story', 'test-case', 'bug', 'review', 'ceremony', 'knowledge',
  'playbook', 'reference', 'template', 'index', 'journal', 'inbox',
  'session', // per-session log under sessions/<session-id>.md (v1.8)
]);

const STATUS_BY_TYPE = {
  story: ['backlog', 'in-progress', 'design-done', 'review-done',
          'execution-done', 'closed', 'blocked', 'cancelled'],
  'test-case': ['draft', 'active', 'retired'],
  bug: ['open', 'assigned', 'fixed', 'verified', 'closed',
        'wontfix', 'duplicate'],
  review: ['in-progress', 'approved', 'changes-requested',
           'rejected', 'done'],
  ceremony: ['active', 'archived'],
  knowledge: ['active', 'draft', 'deprecated'],
  playbook: ['active', 'stub', 'deprecated'],
  reference: ['active', 'pending', 'done', 'archived'],
  session: ['open', 'closed'],
};

const VOCAB_BY_FIELD = {
  priority: ['low', 'medium', 'high', 'critical'],
  last_result: ['passed', 'failed', 'skipped'],
  ac_audit_status: ['pending', 'done'],
  review_status: ['not-reviewed', 'requested', 'in-review', 'changes-requested', 'approved'],
  coverage: ['positive', 'negative', 'edge', 'integration', 'regression'],
  level: ['ui', 'api', 'contract'],
  automation_status: ['auto-soon', 'auto-eventually', 'automated', 'manual-only', 'not-feasible'],
  severity: ['low', 'medium', 'high', 'critical'],
  environment: ['local', 'dev', 'qa', 'prod-readonly'],
  review_outcome: ['in-progress', 'approved', 'changes-requested', 'rejected'],
};

// v2 traceability: known TMS keys for external_ids. Unknown keys are
// tolerated with a warning (new TMSes appear faster than this list).
const KNOWN_EXTERNAL_ID_KEYS = new Set(['xray', 'octane', 'testrail', 'ado', 'zephyr']);

const BRAIN_CONFIG_VOCAB = {
  tms: ['xray-cloud', 'octane', 'testrail', 'ado', 'none', 'tbd'],
  tracker: ['jira', 'ado', 'github', 'none', 'tbd'],
};

const REQUIRED_BY_TYPE = {
  story: ['ticket', 'sprint', 'priority', 'status', 'ac_audit_status', 'linked_test_cases', 'linked_bugs', 'review_status'],
  'test-case': ['id', 'area', 'level', 'coverage', 'status', 'automation_status', 'linked_stories', 'review_status'],
  bug: ['id', 'severity', 'status', 'linked_stories', 'environment'],
  review: ['reviewing_ticket', 'review_outcome', 'reviewed_at', 'status'],
  ceremony: ['ceremony_type', 'date'],
};

// Files exempt from frontmatter requirements (operational, not content).
const SKIP_FILENAMES = new Set([
  'README.md', 'AGENTS.md', 'INDEX.md', 'INBOX.md',
  'JOURNAL.md', 'TODO.md',
  // Cross-AI wrapper files — delegate to AGENTS.md.
  'CLAUDE.md', 'GEMINI.md',
]);

const SKIP_DIRS = new Set([
  '.git', 'node_modules', '.cache', 'versions',
  '.github', // Copilot instructions/prompts use a different frontmatter shape
  '.agents', // canonical skills carry name/description frontmatter, not the content schema
  '.claude', // generated Claude Code adapters — regenerated by sync-agents.mjs
  'templates', // templates carry frontmatter for the NEW file, not their own
]);

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  if (!match) return null;
  const lines = match[1].split(/\r?\n/);
  const out = {};
  for (const line of lines) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    let val = line.slice(colonIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    }
    out[key] = val;
  }
  return out;
}

async function walkMdFiles(dir, baseDir = dir) {
  const result = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return result;
  }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      result.push(...(await walkMdFiles(full, baseDir)));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      if (SKIP_FILENAMES.has(entry.name)) continue;
      result.push(path.relative(baseDir, full));
    }
  }
  return result;
}

// Best-effort PII / secret scan against file body. Warns only —
// false positives are common, so the engineer reviews. The check
// is "did you accidentally paste a token / credit card / IP"
// rather than "is this file safe to ship."
//
// Patterns recognized:
//   - Credit-card-shaped 13–19 digit sequences (Luhn not validated)
//   - SSN-shaped (US): XXX-XX-XXXX
//   - IPv4 addresses (warns; legitimate in env docs but worth a peek)
//   - api_key=, apikey=, secret=, password=, token= assignments
//   - Authorization: Bearer <looks-jwt-like>
//   - Long base64-shaped strings (40+ chars) that look like JWTs/keys
//
// To intentionally include a flagged string (e.g. in a doc that
// explains the pattern), prefix the line with `<!-- pii-ok -->` or
// place the file outside the validated scope.
const PII_PATTERNS = [
  // High-signal, low-false-positive provider keys go first (cheap to fail-fast)
  { name: 'aws-access-key', re: /\bAKIA[0-9A-Z]{16}\b/ },
  { name: 'github-pat', re: /\bgh[pousr]_[A-Za-z0-9]{36,}\b/ },
  { name: 'stripe-live-key', re: /\b(?:sk|pk|rk)_live_[A-Za-z0-9]{20,}\b/ },
  { name: 'stripe-test-key', re: /\b(?:sk|pk|rk)_test_[A-Za-z0-9]{20,}\b/ },
  { name: 'openai-key', re: /\bsk-[A-Za-z0-9]{20,}\b/ },
  // Connection strings with credentials
  { name: 'url-with-credentials', re: /\b[a-z][a-z0-9+]*:\/\/[^\s:/@]+:[^\s/@]+@[^\s\/?#]+/i },
  // Classic PII
  { name: 'credit-card-shaped', re: /\b(?:\d[ -]?){13,19}\b/ },
  { name: 'ssn-shaped (US)', re: /\b\d{3}-\d{2}-\d{4}\b/ },
  // Skip 0.x and 127.x in env files (test fixtures) by not requiring it,
  // but still warn — engineer decides
  { name: 'ipv4-like', re: /\b(?:\d{1,3}\.){3}\d{1,3}\b/ },
  { name: 'api-key-assignment', re: /\b(?:api[_-]?key|apikey|secret|password|access[_-]?token|client[_-]?secret)\s*[:=]\s*["']?[A-Za-z0-9_\-./+=]{8,}/i },
  { name: 'bearer-token', re: /\bAuthorization\s*:\s*Bearer\s+[A-Za-z0-9_\-./+=]{20,}/i },
  // JWT-shaped: three dot-separated base64-ish segments, each 10+
  // chars. Standard JWT pattern (eyJ... is "{" in base64, very
  // common header start).
  { name: 'jwt-shaped', re: /\beyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\b/ },
  // Generic opaque token: 60+ chars, contains both upper and lower
  // case AND a digit. Avoids matching kebab-case filenames.
  { name: 'token-shaped', re: /\b(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z0-9_\-]{60,}={0,3}\b/ },
];

// Lines containing placeholders / example markers skip the entire
// PII scan loop — saves ~6x regex runs per line in docs heavy with
// `<...>` placeholders and `qa+...@example.client.internal` test
// users.
const PLACEHOLDER_RE = /<[^>]+>|\{\{[^}]+\}\}|YYYY-MM-DD|qa\+|example\.client\.internal|placeholder/i;

// Per-line suppressions:
//   <!-- pii-ok -->                  — suppress this single line
//   <!-- pii:ignore-block -->        — start a block of suppressed lines
//   <!-- pii:resume -->              — end the block (PII scan resumes)
//
// Block suppression is for legitimate dummy-data sections in test
// cases (curl examples with example tokens, postgres URLs in
// environments docs, etc.). Use sparingly — the validator is meant
// to be loud.
function scanPII(content) {
  const findings = [];
  const lines = content.split('\n');
  let inIgnoreBlock = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.includes('<!-- pii:ignore-block -->')) {
      inIgnoreBlock = true;
      continue;
    }
    if (line.includes('<!-- pii:resume -->')) {
      inIgnoreBlock = false;
      continue;
    }
    if (inIgnoreBlock) continue;
    if (line.includes('<!-- pii-ok -->') || line.includes('pii-ok:')) continue;
    if (PLACEHOLDER_RE.test(line)) continue;
    for (const { name, re } of PII_PATTERNS) {
      if (re.test(line)) {
        findings.push({ line: i + 1, pattern: name, snippet: line.trim().slice(0, 80) });
        break;
      }
    }
  }
  return findings;
}

function validateFrontmatter(relPath, fm) {
  const errs = [];
  const warns = [];
  if (!fm) {
    errs.push('no frontmatter found (file must start with --- block)');
    return { errs, warns };
  }
  const required = ['title', 'type', 'language', 'tags', 'updated'];
  for (const field of required) {
    if (fm[field] == null || fm[field] === '') {
      errs.push(`missing required field: ${field}`);
    }
  }
  if (fm.type && !ALLOWED_TYPES.has(fm.type)) {
    errs.push(`invalid type: ${fm.type} (allowed: ${[...ALLOWED_TYPES].join(', ')})`);
  }
  if (fm.language && fm.language !== 'en') {
    errs.push(`language must be 'en' (got: ${fm.language})`);
  }
  if (fm.updated && !/^\d{4}-\d{2}-\d{2}$/.test(fm.updated)) {
    errs.push(`updated must be YYYY-MM-DD (got: ${fm.updated})`);
  }
  // status field is type-specific; only validate if both present
  if (fm.type && fm.status && STATUS_BY_TYPE[fm.type]) {
    if (!STATUS_BY_TYPE[fm.type].includes(fm.status)) {
      errs.push(`status '${fm.status}' invalid for type '${fm.type}' (allowed: ${STATUS_BY_TYPE[fm.type].join(', ')})`);
    }
  }
  const requiredByType = REQUIRED_BY_TYPE[fm.type] || [];
  for (const field of requiredByType) {
    if (fm[field] == null || fm[field] === '') {
      errs.push(`missing required field for type '${fm.type}': ${field}`);
    }
  }
  for (const [field, allowed] of Object.entries(VOCAB_BY_FIELD)) {
    if (fm[field] == null || fm[field] === '' || Array.isArray(fm[field])) continue;
    if (!allowed.includes(fm[field])) {
      errs.push(`${field} '${fm[field]}' invalid (allowed: ${allowed.join(', ')})`);
    }
  }

  // v2 traceability fields
  if (fm.last_run && !/^\d{4}-\d{2}-\d{2}$/.test(fm.last_run)) {
    errs.push(`last_run must be YYYY-MM-DD (got: ${fm.last_run})`);
  }
  if (fm.covers_ac !== undefined) {
    const items = Array.isArray(fm.covers_ac)
      ? fm.covers_ac
      : (fm.covers_ac === '' ? [] : [fm.covers_ac]);
    for (const item of items) {
      if (!/^AC-\d+$/.test(item)) {
        errs.push(`covers_ac item '${item}' invalid (expected AC-<n>, e.g. AC-1)`);
      }
    }
  }
  if (typeof fm.external_ids === 'string' && fm.external_ids.trim() !== '' ) {
    const raw = fm.external_ids.trim();
    if (raw.startsWith('{') && raw.endsWith('}')) {
      const inner = raw.slice(1, -1).trim();
      if (inner) {
        for (const pair of inner.split(',')) {
          const key = pair.split(':')[0]?.trim().replace(/^["']|["']$/g, '');
          if (key && !KNOWN_EXTERNAL_ID_KEYS.has(key)) {
            warns.push(`external_ids key '${key}' is not a known TMS (${[...KNOWN_EXTERNAL_ID_KEYS].join(', ')}) — tolerated, double-check the spelling`);
          }
        }
      }
    } else {
      errs.push(`external_ids must be an inline map like {octane: "1042"} (got: ${raw})`);
    }
  }
  return { errs, warns };
}

async function validateFile(relPath, baseDir) {
  const fullPath = path.join(baseDir, relPath);
  let content;
  try {
    content = await fs.readFile(fullPath, 'utf8');
  } catch (err) {
    return { errs: [`cannot read: ${err.message}`], piiFindings: [] };
  }
  const fm = parseFrontmatter(content);
  const { errs, warns } = validateFrontmatter(relPath, fm);
  const piiFindings = scanPII(content);
  return { errs, warns, piiFindings };
}

// brain.config.json — machine-readable brain state (§Config in AGENTS.md).
// Missing file is tolerated (pre-init template state).
async function validateBrainConfig(rootDir) {
  const errs = [];
  const warns = [];
  const p = path.join(rootDir, 'brain.config.json');
  let raw;
  try {
    raw = await fs.readFile(p, 'utf8');
  } catch {
    return { errs, warns, present: false };
  }
  let cfg;
  try {
    cfg = JSON.parse(raw);
  } catch (err) {
    errs.push(`brain.config.json: unparseable JSON (${err.message})`);
    return { errs, warns, present: true };
  }
  for (const [field, allowed] of Object.entries(BRAIN_CONFIG_VOCAB)) {
    const v = cfg[field];
    if (v !== undefined && !allowed.includes(v)) {
      errs.push(`brain.config.json: ${field} '${v}' invalid (allowed: ${allowed.join(', ')})`);
    }
  }
  if (cfg.week_one_done === true) {
    const tbd = ['tms', 'tracker', 'ci'].filter((k) => cfg[k] === 'tbd');
    if (tbd.length) {
      warns.push(`brain.config.json: week_one_done is true but still tbd: ${tbd.join(', ')} — finish the week-one tool inventory`);
    }
  }
  return { errs, warns, present: true };
}

async function main() {
  const args = process.argv.slice(2);
  const strictPII = args.includes('--strict-pii');
  const rootIdx = args.indexOf('--root');
  const rootDir = rootIdx !== -1 ? path.resolve(args[rootIdx + 1]) : REPO_ROOT;
  const positionals = args.filter((a, i) => !a.startsWith('--') && (rootIdx === -1 || i !== rootIdx + 1));
  const target = positionals[0];

  let files;
  if (target) {
    const abs = path.isAbsolute(target) ? target : path.join(rootDir, target);
    let stat = null;
    try {
      stat = await fs.stat(abs);
    } catch {
      // Missing target (e.g. `validate.mjs sessions` before any session
      // file exists) — nothing to validate, treat as clean.
      process.stdout.write(`· ${target} not found — nothing to validate.\n`);
      return;
    }
    if (stat.isDirectory()) {
      // Directory target: walk it, but keep paths relative to REPO_ROOT
      // so messages and exemptions match the whole-repo walk.
      const rels = await walkMdFiles(abs, rootDir);
      files = rels;
    } else {
      files = [path.relative(rootDir, abs)];
    }
  } else {
    files = await walkMdFiles(rootDir);
  }

  let totalErrs = 0;
  let totalPII = 0;
  let totalWarns = 0;
  for (const rel of files) {
    const { errs, warns, piiFindings } = await validateFile(rel, rootDir);
    if (errs.length) {
      process.stderr.write(`\n✗ ${rel}\n`);
      for (const e of errs) {
        process.stderr.write(`  - ${e}\n`);
      }
      totalErrs += errs.length;
    }
    if (warns.length) {
      process.stderr.write(`\n⚠ ${rel}\n`);
      for (const w of warns) {
        process.stderr.write(`  - ${w}\n`);
      }
      totalWarns += warns.length;
    }
    if (piiFindings.length) {
      process.stderr.write(`\n⚠ ${rel} — possible PII / secrets:\n`);
      for (const f of piiFindings) {
        process.stderr.write(`  - line ${f.line} [${f.pattern}]: ${f.snippet}\n`);
      }
      totalPII += piiFindings.length;
    }
  }

  // Whole-repo mode also validates brain.config.json (skipped when a
  // specific target file/dir was requested — focused validation).
  if (!target) {
    const cfg = await validateBrainConfig(rootDir);
    for (const e of cfg.errs) {
      process.stderr.write(`\n✗ ${e}\n`);
      totalErrs++;
    }
    for (const w of cfg.warns) {
      process.stderr.write(`\n⚠ ${w}\n`);
      totalWarns++;
    }
  }

  if (totalErrs > 0) {
    process.stderr.write(`\n${totalErrs} schema violation(s) across ${files.length} file(s).\n`);
    if (totalPII > 0) {
      process.stderr.write(`Plus ${totalPII} possible PII/secret finding(s).\n`);
    }
    process.exit(1);
  }
  if (totalPII > 0) {
    process.stderr.write(`\n${totalPII} possible PII/secret finding(s) across ${files.length} file(s).\n`);
    process.stderr.write('Review each. Add "<!-- pii-ok -->" on the line to suppress a false positive.\n');
    process.stderr.write('Use --strict-pii to fail commit on PII warnings.\n');
    if (strictPII) {
      process.exit(1);
    }
    // Warnings only — exit 0 so the pre-commit hook does not block.
    // The output is still surfaced to the engineer for review.
    return;
  }
  process.stdout.write(`✓ ${files.length} file(s) validated, no issues.\n`);
}

main().catch((err) => {
  process.stderr.write(`validate failed: ${err.message}\n`);
  process.exit(1);
});
